[platformio]
extra_configs =
    secrets.ini
# OTA als Standard-Upload über den mDNS-Hostnamen des ESP32
default_envs = ota

# Gemeinsame Basis-Einstellungen, die automatisch von allen [env:...] geerbt werden
[env]
platform = espressif32
board = esp32dev
framework = arduino
; OTA-fähiges Partitionsschema für das Standard-4-MB-Modul
board_build.partitions = default_ota.csv
board_upload.flash_size = 4MB
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-0001
lib_deps =
    igorantolic/Ai Esp32 Rotary Encoder @ ^1.6
    bblanchon/ArduinoJson @ ^7.0.0
build_flags =
    -D WIFI_SSID=\"${secrets.wifi_ssid}\"
    -D WIFI_PASSWORD=\"${secrets.wifi_password}\"
    -D OTA_HOSTNAME=\"${secrets.ota_hostname}\"
    -D STATIC_IP=\"${secrets.static_ip}\"
    -D STATIC_GATEWAY=\"${secrets.static_gateway}\"
    -D STATIC_SUBNET=\"${secrets.static_subnet}\"

# Spezifische Umgebung für den Kabel-Upload
[env:usb]
upload_protocol = esptool
upload_port = /dev/cu.usbserial-0001
upload_speed = 921600

# Spezifische Umgebung für den Over-The-Air-Upload
; [env:ota]
; upload_protocol = espota
; upload_port = ${secrets.esp32_ip}
; upload_flags =
;     --host_ip=${secrets.host_ip}
;     --host_port=18123
;     --port=3232
;     --debug
;     --progress
;     -i ${secrets.esp32_ip}
;     -r 


[env:ota]
platform = espressif32
board = esp32dev       ; Passe dies an dein exaktes Board an, falls nötig
framework = arduino
upload_protocol = espota
upload_port = ${secrets.esp32_ip}
upload_flags =
    -i ${secrets.esp32_ip}
        --host_ip=${secrets.host_ip}   ; Zwingend wieder aktivieren!
    --debug
    --progress
