[platformio]
extra_configs =
    secrets.ini
default_envs = usb

# Gemeinsame Basis-Einstellungen, die automatisch von allen [env:...] geerbt werden
[env]
platform = espressif32
board = esp32dev
framework = arduino
board_upload.flash_size = 4MB
monitor_speed = 115200

# Erlaubt PlatformIO, den Port beim reinen Kompilieren (pio run) flexibel zu handhaben
monitor_port = /dev/cu.usbserial-0001

lib_deps =
    igorantolic/Ai Esp32 Rotary Encoder @ 1.6.0
    bblanchon/ArduinoJson @ 7.0.4

build_flags =
    -D WIFI_SSID=\"${secrets.wifi_ssid}\"
    -D WIFI_PASSWORD=\"${secrets.wifi_password}\"
    -D STATIC_IP=\"${secrets.static_ip}\"
    -D STATIC_GATEWAY=\"${secrets.static_gateway}\"
    -D STATIC_SUBNET=\"${secrets.static_subnet}\"

# Spezifische Umgebung für den Kabel-Upload
[env:usb]
upload_protocol = esptool
# Der feste Port wird nur beim echten Flashen (pio run -t upload) erzwungen
upload_port = /dev/cu.usbserial-0001
upload_speed = 921600
    