// Generated by Copilot
#include <Arduino.h>
#include <ArduinoOTA.h>
#include <ArduinoJson.h>
#include <WebServer.h>
#include <WiFi.h>
#include "AiEsp32RotaryEncoder.h"

// Generated by Copilot
#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif
#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD ""
#endif
#ifndef OTA_HOSTNAME
#define OTA_HOSTNAME "HB-Uhr"
#endif

// PWM-Ausgaenge gemaess der Pinbelegung in Projektdoku.md.
constexpr int PIN_INST_1 = 13; // Minutenzeiger, 12-V-Schiene
constexpr int PIN_INST_2 = 14; // Stundenzeiger, 3,3-V-Schiene

constexpr int PWM_FREQ = 500;
constexpr int PWM_RESOLUTION = 10;
constexpr int PWM_MAX = (1 << PWM_RESOLUTION) - 1;
constexpr int PWM_MAX_INST_1 = 900; // Kalibriergrenze fuer Instrument 1
constexpr int PWM_MAX_INST_2 = 870; // Hardware-Grenze aus Projektdoku.md

constexpr int ENCODER_A_PIN = 26;
constexpr int ENCODER_B_PIN = 25;
constexpr int ENCODER_SW_PIN = 27;
constexpr int ENCODER_VCC_PIN = -1;
constexpr int ENCODER_STEPS = 4;
constexpr unsigned long WIFI_RECONNECT_INTERVAL_MS = 10000;
constexpr unsigned long WIFI_STARTUP_TIMEOUT_MS = 15000;
constexpr unsigned long BUTTON_DEBOUNCE_MS = 200;

AiEsp32RotaryEncoder rotaryEncoder(
    ENCODER_A_PIN,
    ENCODER_B_PIN,
    ENCODER_SW_PIN,
    ENCODER_VCC_PIN,
    ENCODER_STEPS,
    false); // A/B gegen GND: interne Pull-ups verwenden

int aktuellesInstrument = 1;
int pwmWertInst1 = 0;
int pwmWertInst2 = 0;
int alterWert = -1;
unsigned long letzteWlanPruefung = 0;
unsigned long letzterTasterzeitpunkt = 0;
bool otaAktiv = true;
bool otaDienstBereit = false;

WebServer server(80);

const char WEB_INTERFACE[] PROGMEM = R"rawliteral(
<!doctype html><html lang="de"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>H&amp;B Uhr</title><style>
:root{color-scheme:dark;--bg:#111827;--panel:#1f2937;--line:#374151;--text:#f3f4f6;--muted:#9ca3af;--accent:#f59e0b;--bad:#f87171;--good:#34d399}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top right,#243047,var(--bg) 55%);color:var(--text);font:16px system-ui,sans-serif;min-height:100vh;padding:2rem 1rem}
main{max-width:620px;margin:auto}h1{font-size:clamp(2rem,8vw,3.5rem);letter-spacing:0;margin:0 0 .25rem}p{color:var(--muted)}
.panel{background:rgba(31,41,55,.9);border:1px solid var(--line);padding:1rem;margin:1rem 0}.instruments{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.instrument{min-width:0}.instrument button{width:100%;border:1px solid var(--line);background:#111827;color:var(--text);padding:.8rem;font:inherit;cursor:pointer}.instrument button.active{border-color:var(--accent);color:var(--accent)}label{display:block;color:var(--muted);margin:.8rem 0 .4rem}input{width:100%;background:#111827;border:1px solid var(--line);color:var(--text);font:inherit;padding:.8rem}.message{min-height:1.5rem;color:var(--bad)}.ota{display:flex;align-items:center;justify-content:space-between;gap:1rem;border-top:1px solid var(--line);margin-top:1rem;padding-top:1rem}.ota label{margin:0}.online{color:var(--good)}.offline{color:var(--bad)}small{color:var(--muted)}
</style></head><body><main><h1>H&amp;B Uhr</h1><p>Kalibrierung der analogen Messwerke</p>
<section class="panel"><div class="instruments"><div class="instrument"><button type="button" data-instrument="1">Instrument 1<br><small>Minuten</small></button><form data-form-instrument="1"><label for="pwm1">PWM-Wert</label><input id="pwm1" type="number" min="0" max="900" required></form></div><div class="instrument"><button type="button" data-instrument="2">Instrument 2<br><small>Stunden</small></button><form data-form-instrument="2"><label for="pwm2">PWM-Wert</label><input id="pwm2" type="number" min="0" max="870" required></form></div></div><div class="message" id="message"></div><div class="ota"><span>OTA: <strong id="otaStatus">unbekannt</strong></span><label>Aktiv <input id="otaToggle" type="checkbox"></label></div></section>
<small>Aktualisierung jede Sekunde. PWM-Werte mit Enter setzen.</small></main><script>
let state=null,selected=1;const $=id=>document.getElementById(id);
function choose(n){selected=n;document.querySelectorAll('[data-instrument]').forEach(b=>b.classList.toggle('active',+b.dataset.instrument===n))}
function render(){ $('pwm1').value=state.pwm.instrument1; $('pwm2').value=state.pwm.instrument2; $('pwm1').max=state.limits.instrument1; $('pwm2').max=state.limits.instrument2; choose(state.instrument); $('otaToggle').checked=state.ota.active; $('otaStatus').textContent=state.ota.active?'aktiv':'deaktiviert'; $('otaStatus').className=state.ota.active?'online':'offline' }
async function refresh(){try{let r=await fetch('/api/state');if(!r.ok)throw Error();state=await r.json();render()}catch(e){$('otaStatus').textContent='nicht erreichbar';$('otaStatus').className='offline'}}
async function setPwm(instrument,input){$('message').textContent='';try{let r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instrument:instrument,pwm:Number(input.value)})});let data=await r.json();if(!r.ok)throw Error(data.error||'Fehler');state=data;render()}catch(err){$('message').textContent=err.message}}
document.querySelectorAll('[data-instrument]').forEach(b=>b.onclick=()=>choose(+b.dataset.instrument));document.querySelectorAll('[data-form-instrument]').forEach(form=>form.onsubmit=e=>{e.preventDefault();setPwm(+form.dataset.formInstrument,form.querySelector('input'))});$('otaToggle').onchange=async e=>{try{let r=await fetch('/api/ota',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:e.target.checked})});if(!r.ok)throw Error();state=await r.json();render()}catch(err){e.target.checked=!e.target.checked;$('message').textContent='OTA-Status konnte nicht geändert werden'}};choose(1);refresh();setInterval(refresh,1000);
</script></body></html>)rawliteral";

void schreibeInstrument(int instrument, int wert);

void IRAM_ATTR readEncoderISR()
{
  rotaryEncoder.readEncoder_ISR();
}

void sendeStatus()
{
  JsonDocument status;
  status["instrument"] = aktuellesInstrument;
  status["pwm"]["instrument1"] = pwmWertInst1;
  status["pwm"]["instrument2"] = pwmWertInst2;
  status["limits"]["instrument1"] = PWM_MAX_INST_1;
  status["limits"]["instrument2"] = PWM_MAX_INST_2;
  status["ota"]["active"] = otaAktiv && otaDienstBereit;
  String response;
  serializeJson(status, response);
  server.send(200, "application/json", response);
}

void setzeStatus()
{
  JsonDocument request;
  if (deserializeJson(request, server.arg("plain")) != DeserializationError::Ok)
  {
    server.send(400, "application/json", R"({"error":"Ungueltiges JSON"})");
    return;
  }

  const int instrument = request["instrument"] | 0;
  const int pwm = request["pwm"] | -1;
  if ((instrument != 1 && instrument != 2) || pwm < 0)
  {
    server.send(400, "application/json", R"({"error":"Instrument oder PWM fehlt"})");
    return;
  }

  schreibeInstrument(instrument, pwm);
  aktuellesInstrument = instrument;
  rotaryEncoder.setEncoderValue(instrument == 1 ? pwmWertInst1 : pwmWertInst2);
  alterWert = instrument == 1 ? pwmWertInst1 : pwmWertInst2;
  sendeStatus();
}

void setzeOtaStatus()
{
  JsonDocument request;
  if (deserializeJson(request, server.arg("plain")) != DeserializationError::Ok || !request["active"].is<bool>())
  {
    server.send(400, "application/json", R"({"error":"Ungueltiger OTA-Status"})");
    return;
  }

  otaAktiv = request["active"].as<bool>();
  if (!otaAktiv && otaDienstBereit)
  {
    ArduinoOTA.end();
    otaDienstBereit = false;
  }
  sendeStatus();
}

void aktualisiereOtaDienst()
{
  if (!otaAktiv || WiFi.status() != WL_CONNECTED)
  {
    if (otaDienstBereit)
    {
      ArduinoOTA.end();
      otaDienstBereit = false;
      Serial.println("[OTA] Dienst gestoppt.");
    }
    return;
  }

  if (!otaDienstBereit)
  {
    // Hostnamen explizit setzen (wird für mDNS genutzt)
    ArduinoOTA.setHostname(OTA_HOSTNAME);

    // Zwingend den Port setzen, den auch PlatformIO erwartet!
    ArduinoOTA.setPort(3232);

    // Optionale Sicherheit: Erlaubt detailliertes Loggen im Seriellen Monitor
    ArduinoOTA.onStart([]()
                       { Serial.println("[OTA] Start des Uploads..."); });
    ArduinoOTA.onEnd([]()
                     { Serial.println("\n[OTA] Fertig!"); });
    ArduinoOTA.onProgress([](unsigned int progress, unsigned int total)
                          { Serial.printf("Fortschritt: %u%%\r", (progress / (total / 100))); });
    ArduinoOTA.onError([](ota_error_t error)
                       {
      Serial.printf("Fehler [%u]: ", error);
      if (error == OTA_AUTH_ERROR) Serial.println("Auth fehlgeschlagen");
      else if (error == OTA_BEGIN_ERROR) Serial.println("Begin fehlgeschlagen");
      else if (error == OTA_CONNECT_ERROR) Serial.println("Verbindung fehlgeschlagen");
      else if (error == OTA_RECEIVE_ERROR) Serial.println("Empfang fehlgeschlagen");
      else if (error == OTA_END_ERROR) Serial.println("Ende fehlgeschlagen"); });

    ArduinoOTA.begin();
    otaDienstBereit = true;
    Serial.printf("[OTA] Aktiviert auf %s:3232 mit Hostname '%s'\n",
                  WiFi.localIP().toString().c_str(), OTA_HOSTNAME);
  }
}

// void aktualisiereOtaDienst()
// {
//   if (!otaAktiv || WiFi.status() != WL_CONNECTED)
//   {
//     if (otaDienstBereit)
//     {
//       ArduinoOTA.end();
//       otaDienstBereit = false;
//     }
//     return;
//   }

//   if (!otaDienstBereit)
//   {
//     ArduinoOTA.setHostname(OTA_HOSTNAME);
//     // ArduinoOTA.setPort(8266);
//     ArduinoOTA.begin();
//     otaDienstBereit = true;
//     Serial.printf("OTA aktiv auf %s:3232\n", WiFi.localIP().toString().c_str());
//   }
// }

void starteWlanVerbindung()
{
  WiFi.mode(WIFI_STA);
  if (strlen(WIFI_SSID) == 0)
    return;
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  letzteWlanPruefung = millis();
  Serial.printf("Verbinde mit WLAN '%s' ...\n", WIFI_SSID);
}

void warteAufWlanVerbindung()
{
  const unsigned long startzeit = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - startzeit < WIFI_STARTUP_TIMEOUT_MS)
  {
    delay(100);
  }
}

void halteWlanVerbindung()
{
  if (strlen(WIFI_SSID) == 0 || WiFi.status() == WL_CONNECTED)
    return;
  const unsigned long jetzt = millis();
  if (jetzt - letzteWlanPruefung >= WIFI_RECONNECT_INTERVAL_MS)
  {
    WiFi.disconnect();
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    letzteWlanPruefung = jetzt;
    Serial.println("WLAN getrennt, neuer Verbindungsversuch ...");
  }
}

void richteWebserverEin()
{
  server.on("/", HTTP_GET, []()
            { server.send_P(200, "text/html; charset=utf-8", WEB_INTERFACE); });
  server.on("/api/state", HTTP_GET, sendeStatus);
  server.on("/api/state", HTTP_POST, setzeStatus);
  server.on("/api/ota", HTTP_POST, setzeOtaStatus);
  server.onNotFound([]()
                    { server.send(404, "application/json", R"({"error":"Nicht gefunden"})"); });
  server.begin();
}

int begrenzePwmwert(int wert, int instrument)
{
  const int maximum = instrument == 1 ? PWM_MAX_INST_1 : PWM_MAX_INST_2;
  return constrain(wert, 0, maximum);
}

void schreibeInstrument(int instrument, int wert)
{
  const int begrenzterWert = begrenzePwmwert(wert, instrument);
  if (instrument == 1)
  {
    pwmWertInst1 = begrenzterWert;
    ledcWrite(PIN_INST_1, pwmWertInst1);
  }
  else
  {
    pwmWertInst2 = begrenzterWert;
    ledcWrite(PIN_INST_2, pwmWertInst2);
  }
}

void setup()
{
  Serial.begin(115200);
  delay(1000);
  Serial.println("\n=== Hartmann & Braun Kalibrierung gestartet ===");

  ledcAttach(PIN_INST_1, PWM_FREQ, PWM_RESOLUTION);
  ledcAttach(PIN_INST_2, PWM_FREQ, PWM_RESOLUTION);
  schreibeInstrument(1, 0);
  schreibeInstrument(2, 0);

  starteWlanVerbindung();
  warteAufWlanVerbindung();
  aktualisiereOtaDienst();

  rotaryEncoder.begin();
  rotaryEncoder.setup(readEncoderISR);
  rotaryEncoder.setBoundaries(0, PWM_MAX, false);
  rotaryEncoder.setAcceleration(50);
  rotaryEncoder.setEncoderValue(0);

  richteWebserverEin();

  Serial.println("Steuerung bereit!");
  Serial.println("Druecken: Instrument wechseln");
  Serial.println("Drehen: PWM-Wert aendern");
  Serial.println("Instrument 2 ist auf PWM 870 begrenzt.");
}

void loop()
{
  halteWlanVerbindung();
  server.handleClient();
  aktualisiereOtaDienst();

  // IMMER aufrufen - die Bibliothek verwaltet ihren Status intern selbst.
  ArduinoOTA.handle();

  if (rotaryEncoder.isEncoderButtonClicked() && millis() - letzterTasterzeitpunkt >= BUTTON_DEBOUNCE_MS)
  {
    if (aktuellesInstrument == 1)
    {
      pwmWertInst1 = begrenzePwmwert(rotaryEncoder.readEncoder(), 1);
      aktuellesInstrument = 2;
      rotaryEncoder.setEncoderValue(pwmWertInst2);
      Serial.println("\n[WECHSEL] Instrument 2 (Stunden) gewaehlt.");
    }
    else
    {
      pwmWertInst2 = begrenzePwmwert(rotaryEncoder.readEncoder(), 2);
      aktuellesInstrument = 1;
      rotaryEncoder.setEncoderValue(pwmWertInst1);
      Serial.println("\n[WECHSEL] Instrument 1 (Minuten) gewaehlt.");
    }
    alterWert = -1;
    letzterTasterzeitpunkt = millis();
  }

  if (rotaryEncoder.encoderChanged())
  {
    const int aktuellerWert = begrenzePwmwert(
        rotaryEncoder.readEncoder(), aktuellesInstrument);

    if (aktuellerWert != alterWert)
    {
      schreibeInstrument(aktuellesInstrument, aktuellerWert);
      Serial.printf(
          "Instrument %d | PWM-Wert: %4d / %d\n",
          aktuellesInstrument,
          aktuellerWert,
          aktuellesInstrument == 1 ? PWM_MAX_INST_1 : PWM_MAX_INST_2);
      alterWert = aktuellerWert;
    }
  }
}