// Generated by Copilot
#include <Arduino.h>
#include <WiFi.h>
#include "AiEsp32RotaryEncoder.h"
#include "web_server.h"

// Generated by Copilot
#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif
#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD ""
#endif
#ifndef STATIC_IP
#define STATIC_IP ""
#endif
#ifndef STATIC_GATEWAY
#define STATIC_GATEWAY ""
#endif
#ifndef STATIC_SUBNET
#define STATIC_SUBNET ""
#endif

// PWM-Ausgaenge gemaess der Pinbelegung in Projektdoku.md.
constexpr int PIN_INST_1 = 13; // Minutenzeiger, 12-V-Schiene
constexpr int PIN_INST_2 = 14; // Stundenzeiger, 3,3-V-Schiene

constexpr int PWM_FREQ = 500;
constexpr int PWM_RESOLUTION = 10;
constexpr int PWM_MAX = (1 << PWM_RESOLUTION) - 1;

constexpr int ENCODER_A_PIN = 26;
constexpr int ENCODER_B_PIN = 25;
constexpr int ENCODER_SW_PIN = 27;
constexpr int ENCODER_VCC_PIN = -1;
constexpr int ENCODER_STEPS = 4;
constexpr unsigned long WIFI_RECONNECT_INTERVAL_MS = 10000;
constexpr unsigned long WIFI_STARTUP_TIMEOUT_MS = 15000;
constexpr unsigned long BUTTON_DEBOUNCE_MS = 200;

AiEsp32RotaryEncoder rotaryEncoder(
    ENCODER_A_PIN,
    ENCODER_B_PIN,
    ENCODER_SW_PIN,
    ENCODER_VCC_PIN,
    ENCODER_STEPS,
    false); // A/B gegen GND: interne Pull-ups verwenden

int aktuellesInstrument = 1;
int pwmWertInst1 = 0;
int pwmWertInst2 = 0;
int alterWert = -1;
unsigned long letzteWlanPruefung = 0;
unsigned long letzterTasterzeitpunkt = 0;

void IRAM_ATTR readEncoderISR()
{
  rotaryEncoder.readEncoder_ISR();
}

void starteWlanVerbindung()
{
  WiFi.mode(WIFI_STA);
  if (strlen(WIFI_SSID) == 0)
    return;
  if (strlen(STATIC_IP) > 0)
  {
    IPAddress ip, gateway, subnet;
    const bool ipOk = ip.fromString(STATIC_IP);
    const bool gatewayOk = gateway.fromString(STATIC_GATEWAY);
    const bool subnetOk = subnet.fromString(STATIC_SUBNET);
    if (ipOk && gatewayOk && subnetOk)
    {
      WiFi.config(ip, gateway, subnet);
      Serial.printf("Statische IP konfiguriert: %s\n", STATIC_IP);
    }
    else
    {
      if (!ipOk)
        Serial.printf("[WARNUNG] Ungueltige STATIC_IP: '%s'\n", STATIC_IP);
      if (!gatewayOk)
        Serial.printf("[WARNUNG] Ungueltige STATIC_GATEWAY: '%s'\n", STATIC_GATEWAY);
      if (!subnetOk)
        Serial.printf("[WARNUNG] Ungueltige STATIC_SUBNET: '%s'\n", STATIC_SUBNET);
      Serial.println("[WARNUNG] Statische IP-Konfiguration ungueltig, verwende DHCP.");
    }
  }

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  letzteWlanPruefung = millis();
  Serial.printf("Verbinde mit WLAN '%s' ...\n", WIFI_SSID);
}

void warteAufWlanVerbindung()
{
  const unsigned long startzeit = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - startzeit < WIFI_STARTUP_TIMEOUT_MS)
  {
    delay(100);
  }
}

void halteWlanVerbindung()
{
  if (strlen(WIFI_SSID) == 0 || WiFi.status() == WL_CONNECTED)
    return;
  const unsigned long jetzt = millis();
  if (jetzt - letzteWlanPruefung >= WIFI_RECONNECT_INTERVAL_MS)
  {
    WiFi.disconnect();
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    letzteWlanPruefung = jetzt;
    Serial.println("WLAN getrennt, neuer Verbindungsversuch ...");
  }
}

void schreibeInstrument(int instrument, int wert)
{
  if (instrument == 1)
  {
    pwmWertInst1 = constrain(wert, 0, PWM_MAX);
    ledcWrite(PIN_INST_1, pwmWertInst1);
  }
  else
  {
    pwmWertInst2 = constrain(wert, 0, PWM_MAX);
    ledcWrite(PIN_INST_2, pwmWertInst2);
  }
}

WebServerState leseWebStatus()
{
  return {aktuellesInstrument, pwmWertInst1, pwmWertInst2};
}

bool schreibeWebPwm(int instrument, int wert)
{
  if ((instrument != 1 && instrument != 2) || wert < 0 || wert > PWM_MAX)
    return false;

  schreibeInstrument(instrument, wert);
  aktuellesInstrument = instrument;
  rotaryEncoder.setEncoderValue(wert);
  alterWert = wert;
  return true;
}

void setup()
{
  Serial.begin(115200);
  delay(1000);
  Serial.println("\n=== Hartmann & Braun Kalibrierung gestartet ===");

  ledcAttach(PIN_INST_1, PWM_FREQ, PWM_RESOLUTION);
  ledcAttach(PIN_INST_2, PWM_FREQ, PWM_RESOLUTION);
  schreibeInstrument(1, 0);
  schreibeInstrument(2, 0);

  starteWlanVerbindung();
  warteAufWlanVerbindung();
  rotaryEncoder.begin();
  rotaryEncoder.setup(readEncoderISR);
  rotaryEncoder.setBoundaries(0, PWM_MAX, false);
  rotaryEncoder.setAcceleration(50);
  rotaryEncoder.setEncoderValue(0);

  richteWebserverEin(leseWebStatus, schreibeWebPwm);

  Serial.println("Steuerung bereit!");
  Serial.println("Druecken: Instrument wechseln");
  Serial.println("Drehen: PWM-Wert aendern");
  Serial.printf("PWM-Bereich fuer beide Instrumente: 0..%d.\n", PWM_MAX);
}

void loop()
{
  halteWlanVerbindung();
  bearbeiteWebserver();

  if (rotaryEncoder.isEncoderButtonClicked() && millis() - letzterTasterzeitpunkt >= BUTTON_DEBOUNCE_MS)
  {
    if (aktuellesInstrument == 1)
    {
      pwmWertInst1 = constrain(rotaryEncoder.readEncoder(), 0, PWM_MAX);
      aktuellesInstrument = 2;
      rotaryEncoder.setEncoderValue(pwmWertInst2);
      Serial.println("\n[WECHSEL] Instrument 2 (Stunden) gewaehlt.");
    }
    else
    {
      pwmWertInst2 = constrain(rotaryEncoder.readEncoder(), 0, PWM_MAX);
      aktuellesInstrument = 1;
      rotaryEncoder.setEncoderValue(pwmWertInst1);
      Serial.println("\n[WECHSEL] Instrument 1 (Minuten) gewaehlt.");
    }
    alterWert = -1;
    letzterTasterzeitpunkt = millis();
  }

  if (rotaryEncoder.encoderChanged())
  {
    const int aktuellerWert = constrain(rotaryEncoder.readEncoder(), 0, PWM_MAX);

    if (aktuellerWert != alterWert)
    {
      schreibeInstrument(aktuellesInstrument, aktuellerWert);
      Serial.printf(
          "Instrument %d | PWM-Wert: %4d / %d\n",
          aktuellesInstrument,
          aktuellerWert,
          PWM_MAX);
      alterWert = aktuellerWert;
    }
  }
}