// Generated by Copilot
#include "web_server.h"

#include <ArduinoJson.h>
#include <WebServer.h>

namespace
{
  WebServer server(80);
  WebStateReader leseStatus = nullptr;
  WebPwmWriter schreibePwm = nullptr;

  const char WEB_INTERFACE[] PROGMEM = R"rawliteral(
<!doctype html><html lang="de"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>H&amp;B Uhr</title><style>
:root{color-scheme:dark;--bg:#111827;--panel:#1f2937;--line:#374151;--text:#f3f4f6;--muted:#9ca3af;--accent:#f59e0b;--bad:#f87171}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top right,#243047,var(--bg) 55%);color:var(--text);font:16px system-ui,sans-serif;min-height:100vh;padding:2rem 1rem}
main{max-width:620px;margin:auto}h1{font-size:clamp(2rem,8vw,3.5rem);letter-spacing:0;margin:0 0 .25rem}p{color:var(--muted)}
.panel{background:rgba(31,41,55,.9);border:1px solid var(--line);padding:1rem;margin:1rem 0}.instruments{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.instrument{min-width:0}.instrument button{width:100%;border:1px solid var(--line);background:#111827;color:var(--text);padding:.8rem;font:inherit;cursor:pointer}.instrument button.active{border-color:var(--accent);color:var(--accent)}label{display:block;color:var(--muted);margin:.8rem 0 .4rem}input{width:100%;background:#111827;border:1px solid var(--line);color:var(--text);font:inherit;padding:.8rem}.message{min-height:1.5rem;color:var(--bad)}small{color:var(--muted)}
</style></head><body><main><h1>H&amp;B Uhr</h1><p>Kalibrierung der analogen Messwerke</p>
<section class="panel"><div class="instruments"><div class="instrument"><button type="button" data-instrument="1">Instrument 1<br><small>Minuten</small></button><form data-form-instrument="1"><label for="pwm1">PWM-Wert</label><input id="pwm1" type="number" min="0" max="1023" required></form></div><div class="instrument"><button type="button" data-instrument="2">Instrument 2<br><small>Stunden</small></button><form data-form-instrument="2"><label for="pwm2">PWM-Wert</label><input id="pwm2" type="number" min="0" max="1023" required></form></div></div><div class="message" id="message"></div></section>
<small>Aktualisierung jede Sekunde. PWM-Werte mit Enter setzen.</small></main><script>
let state=null;const $=id=>document.getElementById(id);
function choose(n){document.querySelectorAll('[data-instrument]').forEach(b=>b.classList.toggle('active',+b.dataset.instrument===n))}
function render(){ $('pwm1').value=state.pwm.instrument1; $('pwm2').value=state.pwm.instrument2; choose(state.instrument) }
async function refresh(){try{let r=await fetch('/api/state');if(!r.ok)throw Error();state=await r.json();render()}catch(e){$('message').textContent='Webserver nicht erreichbar'}}
async function setPwm(instrument,input){$('message').textContent='';try{let r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instrument:instrument,pwm:Number(input.value)})});let data=await r.json();if(!r.ok)throw Error(data.error||'Fehler');state=data;render()}catch(err){$('message').textContent=err.message}}
document.querySelectorAll('[data-instrument]').forEach(b=>b.onclick=()=>choose(+b.dataset.instrument));document.querySelectorAll('[data-form-instrument]').forEach(form=>form.onsubmit=e=>{e.preventDefault();setPwm(+form.dataset.formInstrument,form.querySelector('input'))});choose(1);refresh();setInterval(refresh,1000);
</script></body></html>)rawliteral";

  void sendeStatus()
  {
    const WebServerState state = leseStatus();
    JsonDocument status;
    status["instrument"] = state.instrument;
    status["pwm"]["instrument1"] = state.pwmInstrument1;
    status["pwm"]["instrument2"] = state.pwmInstrument2;
    String response;
    serializeJson(status, response);
    server.send(200, "application/json", response);
  }

  void setzeStatus()
  {
    JsonDocument request;
    if (deserializeJson(request, server.arg("plain")) != DeserializationError::Ok)
    {
      server.send(400, "application/json", R"({"error":"Ungueltiges JSON"})");
      return;
    }

    const int instrument = request["instrument"] | 0;
    const int pwm = request["pwm"] | -1;
    if ((instrument != 1 && instrument != 2) || pwm < 0 || pwm > 1023 || !schreibePwm(instrument, pwm))
    {
      server.send(400, "application/json", R"({"error":"Instrument oder PWM ungueltig"})");
      return;
    }

    sendeStatus();
  }
}

void richteWebserverEin(WebStateReader stateReader, WebPwmWriter pwmWriter)
{
  leseStatus = stateReader;
  schreibePwm = pwmWriter;
  server.on("/", HTTP_GET, []()
            { server.send_P(200, "text/html; charset=utf-8", WEB_INTERFACE); });
  server.on("/api/state", HTTP_GET, sendeStatus);
  server.on("/api/state", HTTP_POST, setzeStatus);
  server.onNotFound([]()
                    { server.send(404, "application/json", R"({"error":"Nicht gefunden"})"); });
  server.begin();
}

void bearbeiteWebserver()
{
  server.handleClient();
}
