// Generated by Copilot
#ifndef WEB_SERVER_H
#define WEB_SERVER_H

struct WebServerState
{
  int instrument;
  int pwmInstrument1;
  int pwmInstrument2;
};

using WebStateReader = WebServerState (*)();
using WebPwmWriter = bool (*)(int instrument, int pwm);

void richteWebserverEin(WebStateReader stateReader, WebPwmWriter pwmWriter);
void bearbeiteWebserver();

#endif
